    // (generated by Cascade) Note: this file is a Sokol '#pragma sokol' shader, not sg_shader C code.
//------------------------------------------------------------------------------
//  Sprite shader in Sokol '#pragma sokol' format.
//------------------------------------------------------------------------------
#pragma sokol @header const m = @import("math.zig")
#pragma sokol @ctype mat4 m.Mat4

#pragma sokol @vs vs
layout(binding=0) uniform vs_params {
    mat4 mvp;
};

in vec4 pos;
in vec2 texcoord0;
in vec4 color0;

out vec2 uv;
out vec4 color;

void main() {
    gl_Position = mvp * pos;
    uv = texcoord0;
    color = color0;
}
#pragma sokol @end

#pragma sokol @fs fs
layout(binding=0) uniform texture2D tex;
layout(binding=0) uniform sampler smp;

in vec2 uv;
in vec4 color;
out vec4 frag_color;

void main() {
    vec4 tex_color = texture(sampler2D(tex, smp), uv);
    frag_color = tex_color * color;
}
#pragma sokol @end

#pragma sokol @program sprite vs fs